//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Live.com_Сombiner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("in\\UserAgent.txt")]
        public string UserAgentFileBox {
            get {
                return ((string)(this["UserAgentFileBox"]));
            }
            set {
                this["UserAgentFileBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("in\\Proxy.txt")]
        public string ProxyFilePathBox {
            get {
                return ((string)(this["ProxyFilePathBox"]));
            }
            set {
                this["ProxyFilePathBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://bing.com/")]
        public string ProxyCheckLinkBox {
            get {
                return ((string)(this["ProxyCheckLinkBox"]));
            }
            set {
                this["ProxyCheckLinkBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OperatingModeBox {
            get {
                return ((int)(this["OperatingModeBox"]));
            }
            set {
                this["OperatingModeBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProxySourceBox {
            get {
                return ((int)(this["ProxySourceBox"]));
            }
            set {
                this["ProxySourceBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProxyModeBox {
            get {
                return ((int)(this["ProxyModeBox"]));
            }
            set {
                this["ProxyModeBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TypeOfProxyBox {
            get {
                return ((int)(this["TypeOfProxyBox"]));
            }
            set {
                this["TypeOfProxyBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int MinPauseNumeric {
            get {
                return ((int)(this["MinPauseNumeric"]));
            }
            set {
                this["MinPauseNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int MaxPauseNumeric {
            get {
                return ((int)(this["MaxPauseNumeric"]));
            }
            set {
                this["MaxPauseNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CountRequestNumeric {
            get {
                return ((int)(this["CountRequestNumeric"]));
            }
            set {
                this["CountRequestNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CountThreadNumeric {
            get {
                return ((int)(this["CountThreadNumeric"]));
            }
            set {
                this["CountThreadNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableLogBox {
            get {
                return ((bool)(this["DisableLogBox"]));
            }
            set {
                this["DisableLogBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ae23daf19c9e65577bb4549070c8c16b")]
        public string ClientKeyBox {
            get {
                return ((string)(this["ClientKeyBox"]));
            }
            set {
                this["ClientKeyBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxCountMessageToGroupsNumeric {
            get {
                return ((int)(this["MaxCountMessageToGroupsNumeric"]));
            }
            set {
                this["MaxCountMessageToGroupsNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MaxCountMessageToLSNumeric {
            get {
                return ((int)(this["MaxCountMessageToLSNumeric"]));
            }
            set {
                this["MaxCountMessageToLSNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MessageForSpamGroup {
            get {
                return ((string)(this["MessageForSpamGroup"]));
            }
            set {
                this["MessageForSpamGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MessageForSpamLS {
            get {
                return ((string)(this["MessageForSpamLS"]));
            }
            set {
                this["MessageForSpamLS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("in\\NameSurname.txt")]
        public string NameSurnameBox {
            get {
                return ((string)(this["NameSurnameBox"]));
            }
            set {
                this["NameSurnameBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("in\\Passwords.txt")]
        public string PasswordFileBox {
            get {
                return ((string)(this["PasswordFileBox"]));
            }
            set {
                this["PasswordFileBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoginGenerateCheckBox {
            get {
                return ((bool)(this["LoginGenerateCheckBox"]));
            }
            set {
                this["LoginGenerateCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PasswordGenerateCheckBox {
            get {
                return ((bool)(this["PasswordGenerateCheckBox"]));
            }
            set {
                this["PasswordGenerateCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CountAccountNumeric {
            get {
                return ((int)(this["CountAccountNumeric"]));
            }
            set {
                this["CountAccountNumeric"] = value;
            }
        }
    }
}
